# Text Representation

Text representation in NLP means converting text into a numerical form that a machine learning model can understand and process.

## What is Embedding?

Embeddings in NLP is a technique where individual words are represented as real-valued vectors and captures inter-word semantics.


In this notebook, We going to intreduce 2 techniques for embedding. These techniques will be used for a machine learning models such as SVM, Random forest, ... ect.

<img src="https://drive.google.com/uc?export=view&id=1jd0u_sGppDKqBYbhtJfGxp14lnUWUTTw" width="900">

# 1- TF-IDF

<img src="https://drive.google.com/uc?export=view&id=1saSt0mMgOQ2ybbTms1lu_ruhUcBWkKzL" width="500">

TF-IDF stands for term frequency-inverse document frequency. It is a measure that discounts common words. Used in the fields of information retrieval (IR) and machine learning, that can quantify the importance of words in a document amongst a collection of documents (also known as a corpus).

### Components of TF-IDF

1. **TF (Term Frequency):**  
   Measures how frequently a term appears in a document.


$$ \text{TF}(t, d) = \frac{\text{Number of times term } t \text{ appears in document } d}{\text{Total number of terms in document } d} $$


2. **IDF (Inverse Document Frequency):**  
   Measures how important a term is across all documents. Words that appear in many documents get lower scores.

$$    \text{IDF}(t) = \log \left(\frac{\text{Number of all documents N}}{\text{Number of documents containing the term } t}\right) $$

<img src="https://drive.google.com/uc?export=view&id=1JqPILC8TTh3yDQZCSuPNXwm6ER5YeJFh" width="900">

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
doc_1 = "Data is the oil of the digital economy"
doc_2 = "Data is a new oil"

data = [doc_1, doc_2]

In [3]:
tfidf = TfidfVectorizer()
result = tfidf.fit_transform(data) # returns sparce matrix

In [4]:
import pandas as pd
df = pd.DataFrame(result.toarray(), columns=tfidf.get_feature_names_out())
df

       data  digital  economy        is       new       of       oil      the
0  0.243777  0.34262  0.34262  0.243777  0.000000  0.34262  0.243777  0.68524
1  0.448321  0.00000  0.00000  0.448321  0.630099  0.00000  0.448321  0.00000

# Cosine similarity

In NLP, Cosine similarity is a metric used to measure how similar the documents are.


$$ \text{cosine similarity} = \frac{A \cdot B}{\|A\| \times \|B\|} $$

Where:  
$ A \cdot B $  = dot product of vectors A and B  
$ \|A\| $ = magnitude (length) of vector A  
$ \|B\| $ =  magnitude (length) of vector B

#### Intuition

- If vectors point in the **same direction**, cosine similarity = **1** (maximum similarity).
- If vectors are **orthogonal (90° apart)**, cosine similarity = **0** (no similarity).

<img src="https://drive.google.com/uc?export=view&id=1b-o8CVfHBsjUGY_hXmxevU91gHidIuxO" width="900">

In [5]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [6]:
# Sample text data (replace with your own documents)

doc_1 = "Data is the oil of the digital economy"
doc_2 = "Data is a new oil"

data = [doc_1, doc_2]

In [7]:
tfidf_vectorizer = TfidfVectorizer() # Create a CountVectorizer instance
vector_matrix = tfidf_vectorizer.fit_transform(data) # Fit and transform the documents into numerical vectors

In [8]:
# Calculate the cosine similarity between the documents
cosine_similarity_matrix = cosine_similarity(vector_matrix)

df_cosine = pd.DataFrame(data=cosine_similarity_matrix, index=data, columns=data)

df_cosine

,Data is the oil of the digital economy,Data is a new oil
Data is the oil of the digital economy,1.000000,0.327871
Data is a new oil,0.327871,1.000000

# 2- What is Word2vec?

Word2Vec consists of models for generating word embedding. These models are two-layer neural networks having one input layer, one hidden layer, and one output layer.

Word2Vec utilizes two architectures :
1. CBOW (Continuous Bag of Words)
2. **Skip Gram**
<img src="https://drive.google.com/uc?export=view&id=1K38nEu_KhgtSJuG2RySwc6U5AAjVAgWZ" width="600">


Run this command in terminal to install
> pip install gensim

We will use fake and real news dataset to do our expirament. You can find the dataset here: https://www.kaggle.com/datasets/clmentbisaillon/fake-and-real-news-dataset?select=True.csv

In [9]:
import pandas as pd
import nltk
import numpy as np
import gensim

from nltk.tokenize import word_tokenize

In [10]:
import kagglehub
import glob

_news_path = kagglehub.dataset_download("clmentbisaillon/fake-and-real-news-dataset")
_true_csv = [p for p in glob.glob(f"{_news_path}/*.csv") if 'True' in p][0]

df = pd.read_csv(_true_csv, engine='python', on_bad_lines='skip') #fake-and-real-news-dataset-true.csv
df.head()

Downloading to /Users/alwaleed/.cache/kagglehub/datasets/clmentbisaillon/fake-and-real-news-dataset/1.archive...

  0%|          | 0.00/41.0M [00:00<?, ?B/s]

  2%|▏         | 1.00M/41.0M [00:03<02:05, 334kB/s]

  5%|▍         | 2.00M/41.0M [00:05<01:48, 377kB/s]

  7%|▋         | 3.00M/41.0M [00:08<01:53, 350kB/s]

 10%|▉         | 4.00M/41.0M [00:11<01:51, 349kB/s]

 12%|█▏        | 5.00M/41.0M [00:14<01:42, 367kB/s]

 15%|█▍        | 6.00M/41.0M [00:19<02:07, 288kB/s]

 17%|█▋        | 7.00M/41.0M [00:26<02:36, 228kB/s]

 17%|█▋        | 7.00M/41.0M [00:40<02:36, 228kB/s]

 20%|█▉        | 8.00M/41.0M [00:42<04:37, 125kB/s]

 22%|██▏       | 9.00M/41.0M [00:56<05:23, 104kB/s]

 24%|██▍       | 10.0M/41.0M [00:57<03:43, 146kB/s]

 27%|██▋       | 11.0M/41.0M [00:57<02:32, 206kB/s]

 29%|██▉       | 12.0M/41.0M [00:58<01:45, 287kB/s]

 32%|███▏      | 13.0M/41.0M [00:58<01:13, 401kB/s]

 34%|███▍      | 14.0M/41.0M [00:58<00:51, 554kB/s]

 37%|███▋      | 15.0M/41.0M [00:58<00:36, 755kB/s]

 39%|███▉      | 16.0M/41.0M [00:58<00:25, 1.01MB/s]

 41%|████▏     | 17.0M/41.0M [00:59<00:19, 1.32MB/s]

 44%|████▍     | 18.0M/41.0M [00:59<00:14, 1.68MB/s]

 46%|████▋     | 19.0M/41.0M [00:59<00:11, 1.99MB/s]

 49%|████▉     | 20.0M/41.0M [01:00<00:10, 2.19MB/s]

 51%|█████     | 21.0M/41.0M [01:00<00:08, 2.59MB/s]

 54%|█████▎    | 22.0M/41.0M [01:00<00:06, 2.94MB/s]

 56%|█████▌    | 23.0M/41.0M [01:00<00:06, 3.03MB/s]

 59%|█████▊    | 24.0M/41.0M [01:01<00:05, 3.34MB/s]

 61%|██████    | 25.0M/41.0M [01:01<00:04, 3.76MB/s]

 63%|██████▎   | 26.0M/41.0M [01:01<00:03, 4.07MB/s]

 66%|██████▌   | 27.0M/41.0M [01:01<00:03, 4.31MB/s]

 68%|██████▊   | 28.0M/41.0M [01:02<00:04, 3.00MB/s]

 71%|███████   | 29.0M/41.0M [01:02<00:04, 2.88MB/s]

 73%|███████▎  | 30.0M/41.0M [01:03<00:04, 2.81MB/s]

 76%|███████▌  | 31.0M/41.0M [01:03<00:03, 3.29MB/s]

 78%|███████▊  | 32.0M/41.0M [01:03<00:02, 3.75MB/s]

 81%|████████  | 33.0M/41.0M [01:03<00:02, 4.18MB/s]

 83%|████████▎ | 34.0M/41.0M [01:03<00:01, 4.50MB/s]

 85%|████████▌ | 35.0M/41.0M [01:04<00:01, 4.84MB/s]

 88%|████████▊ | 36.0M/41.0M [01:04<00:01, 5.04MB/s]

 90%|█████████ | 37.0M/41.0M [01:04<00:00, 5.24MB/s]

 93%|█████████▎| 38.0M/41.0M [01:04<00:00, 5.29MB/s]

 95%|█████████▌| 39.0M/41.0M [01:04<00:00, 5.29MB/s]

 98%|█████████▊| 40.0M/41.0M [01:04<00:00, 5.56MB/s]

100%|██████████| 41.0M/41.0M [01:05<00:00, 5.23MB/s]

100%|██████████| 41.0M/41.0M [01:05<00:00, 659kB/s]

Extracting files...

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [11]:
tokens = []

for i in df['text']:
    token = word_tokenize(i)
    tokens.append(token)

In [12]:
w2v = gensim.models.Word2Vec(tokens, min_count=1, vector_size=100, window=5, sg=1)

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

In [13]:
print("Cosine similarity between 'provide' and 'program' - Skip Gram : ",w2v.wv.similarity('provide', 'program'))

Cosine similarity between 'provide' and 'program' - Skip Gram :  0.41961893

In [14]:
print("words that similar to 'program' - Skip Gram : ",w2v.wv.most_similar('program'))

words that similar to 'program' - Skip Gram :  [('programme', 0.8191462159156799), ('programs', 0.7989629507064819), ('arsenal', 0.7102507948875427), ('modernization', 0.6967984437942505), ('bond-buying', 0.6840164661407471), ('curbed', 0.6736188530921936), ('curtail', 0.6705663204193115), ('guest-worker', 0.6611300110816956), ('accelerates', 0.6592375040054321), ('entitlement', 0.6591554880142212)]

# Tasks

### Task 1: Cosine Similarity
Use the Cosine Similarity method to determine how similar the following sentences are.

'This is the first document.',  
'This document is the second document.',  
'And this is the third one.',  
'Is this the first document?'

In [15]:
# Task 1: Cosine Similarity
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

docs_t1 = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]

vectorizer_t1 = TfidfVectorizer()
vectors_t1 = vectorizer_t1.fit_transform(docs_t1)

sim_matrix_t1 = cosine_similarity(vectors_t1)
df_sim_t1 = pd.DataFrame(sim_matrix_t1, index=docs_t1, columns=docs_t1)
df_sim_t1

,This is the first document.,This document is the second document.,And this is the third one.,Is this the first document?
This is the first document.,1.000000,0.646926,0.307772,1.000000
This document is the second document.,0.646926,1.000000,0.225240,0.646926
And this is the third one.,0.307772,0.225240,1.000000,0.307772
Is this the first document?,1.000000,0.646926,0.307772,1.000000

### Task 2: TF-IDF
Use tf-idf method on the sentences below to determine the important words.

'data science is one of the most important fields of science',  
'this is one of the best data science courses',  
'data scientists analyze data'

In [16]:
# Task 2: TF-IDF
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

docs_t2 = [
    'data science is one of the most important fields of science',
    'this is one of the best data science courses',
    'data scientists analyze data',
]

tfidf_t2 = TfidfVectorizer()
result_t2 = tfidf_t2.fit_transform(docs_t2)

df_t2 = pd.DataFrame(result_t2.toarray(), columns=tfidf_t2.get_feature_names_out())
df_t2

,analyze,best,courses,data,fields,important,is,most,of,one,science,scientists,the,this
0,0.000000,0.000000,0.000000,0.189526,0.320895,0.320895,0.244049,0.320895,0.488098,0.244049,0.488098,0.000000,0.244049,0.000000
1,0.000000,0.400294,0.400294,0.236420,0.000000,0.000000,0.304434,0.000000,0.304434,0.304434,0.304434,0.000000,0.304434,0.400294
2,0.542701,0.000000,0.000000,0.641055,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.542701,0.000000,0.000000

## Word2vec

### Task 3:

Download the Simpsons dataset **(simpsons_script_lines.csv)** and apply the preprocessing procedure.  
Use the **'spoken_words'** column.
```
def clean_text(text):
    text = text.lower()
    text = re.sub(r"[0-9]", '', text)
    text = re.sub(r"[)(,”“.’$-]", '', text)
    return text
```
Create a skip gram Word2Vec model as below.
```
Skip_gram_model = gensim.models.Word2Vec(tokens, min_count = 1, vector_size = 100, window = 5, sg = 1)

In [17]:
# Task 3: Simpsons dataset + Skip-Gram Word2Vec
import re
import pandas as pd
import gensim
from nltk.tokenize import word_tokenize

simpsons_df = pd.read_csv('dataset/simpsons_script_lines.csv', on_bad_lines='skip')
simpsons_df = simpsons_df.dropna(subset=['spoken_words'])

def clean_text(text):
    text = text.lower()
    text = re.sub(r"[0-9]", '', text)
    text = re.sub(r"[)(,\u201d\u201c.\u2019$-]", '', text)
    return text

simpsons_df['clean'] = simpsons_df['spoken_words'].apply(clean_text)

tokens = [word_tokenize(t) for t in simpsons_df['clean']]

Skip_gram_model = gensim.models.Word2Vec(tokens, min_count=1, vector_size=100, window=5, sg=1)
print("Vocabulary size:", len(Skip_gram_model.wv))

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

Vocabulary size: 44175

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

### Task 4

Use: wv.most_similar() method to :

1.	Find the words similar to “homer”.

2.	Find the words similar to “marge”.

3. Find the words similar to “bart”

In [18]:
# Task 4: words similar to homer / marge / bart
print("Similar to 'homer':", Skip_gram_model.wv.most_similar('homer'))
print("\nSimilar to 'marge':", Skip_gram_model.wv.most_similar('marge'))
print("\nSimilar to 'bart':", Skip_gram_model.wv.most_similar('bart'))

Similar to 'homer': [('abe', 0.8821682929992676), ('marge', 0.8509763479232788), ('bart', 0.827056884765625), ('eliza', 0.8216751217842102), ('grampa', 0.8161013722419739), ('becky', 0.8134793639183044), ('allison', 0.8119462728500366), ('ned', 0.807066798210144), ('mindy', 0.8068459033966064), ('bartholomew', 0.8057154417037964)]

Similar to 'marge': [('abe', 0.8631612658500671), ('homer', 0.8509764075279236), ('becky', 0.8405018448829651), ('sweetheart', 0.839729368686676), ('sweetie', 0.8322742581367493), ('lisa', 0.8227635025978088), ('lurleen', 0.8205889463424683), ('maude', 0.8181191086769104), ('eliza', 0.8176379799842834), ('midge', 0.8165373206138611)]

Similar to 'bart': [('milhouse', 0.8664434552192688), ('lisa', 0.8561581969261169), ('abe', 0.8393954038619995), ('grampa', 0.8333950042724609), ('eliza', 0.8310465216636658), ('allison', 0.8295063376426697), ('homer', 0.8270569443702698), ('laddie', 0.8227710723876953), ('kirk', 0.8191306591033936), ('becky', 0.8190287947654724)]

### Task 5

Use the wv.doesnt_match() method to :

1.	Find which of 'jimbo', 'milhouse’, and 'kearney’ does not belong to the list.

3.	Find the odd one among "nelson", "bart", and "milhouse".

4.	Find the odd one among ‘homer', 'patty', and ‘selma'.

*Hint: You need to pass the strings as List*

In [19]:
# Task 5: doesnt_match
print("Odd one out among ['jimbo','milhouse','kearney']:",
      Skip_gram_model.wv.doesnt_match(['jimbo', 'milhouse', 'kearney']))

print("Odd one out among ['nelson','bart','milhouse']:",
      Skip_gram_model.wv.doesnt_match(['nelson', 'bart', 'milhouse']))

print("Odd one out among ['homer','patty','selma']:",
      Skip_gram_model.wv.doesnt_match(['homer', 'patty', 'selma']))

Odd one out among ['jimbo','milhouse','kearney']: milhouse
Odd one out among ['nelson','bart','milhouse']: nelson
Odd one out among ['homer','patty','selma']: homer